"

"
Class {
	#name : #GLMTestAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'parameter'
	],
	#category : #Glamour-Tests-Core,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMTestAnnouncement>>parameter [
	^ parameter
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMTestAnnouncement>>parameter: anObject [
	parameter := anObject
]
