"
This class offers a number of extra icons that work with the Glamorous Theme.
"
Class {
	#name : #GLMUIThemeExtraIcons,
	#superclass : #Model,
	#classInstVars : [
		'icons'
	],
	#category : #Glamour-Morphic-Theme,
	#timestamp : 'TudorGirba 1/30/2011 22:55'
}

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousAccept [
	^ self iconNamed: #glamorousAccept
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousAdd [
	^ self iconNamed: #glamorousAdd
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousAlarm [
	^ self iconNamed: #glamorousAlarm
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousBookmark [
	^ self iconNamed: #glamorousBookmark
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousBrowse [
	^ self iconNamed: #glamorousBrowse
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousBug [
	^ self iconNamed: #glamorousBug
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousCancel [
	^ self iconNamed: #glamorousCancel
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousClose [
	^ self iconNamed: #glamorousClose
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousDown [
	^ self iconNamed: #glamorousDown
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousDropDown [
	^ self iconNamed: #glamorousDropDown
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousEdit [
	^ self iconNamed: #glamorousEdit
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousExample [
	^ self iconNamed: #glamorousExample
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousFolder [
	^ self iconNamed: #glamorousFolder
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousGo [
	^ self iconNamed: #glamorousGo
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousGrayCircle [
	^ self iconNamed: #glamorousGrayCircle
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousGrayCircleEmpty [
	^ self iconNamed: #glamorousGrayCircleEmpty
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousGreenCircle [
	^ self iconNamed: #glamorousGreenCircle
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousHelp [
	^ self iconNamed: #glamorousHelp
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousInspect [
	^ self iconNamed: #glamorousInspect
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousInto [
	^ self iconNamed: #glamorousInto
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousLargeGrayCircleEmphasized [
	^ self iconNamed: #glamorousLargeGrayCircleEmphasized
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousLeft [
	^ self iconNamed: #glamorousLeft
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousLeftSide [
	^ self iconNamed: #glamorousLeftSide
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousMore [
	^ self iconNamed: #glamorousMore
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousOpen [
	^ self iconNamed: #glamorousOpen
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousOpenFromUrl [
	^ self iconNamed: #glamorousOpenFromUrl
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousOver [
	^ self iconNamed: #glamorousOver
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousPlay [
	^ self iconNamed: #glamorousPlay
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRedCircle [
	^ self iconNamed: #glamorousRedCircle
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRedo [
	^ self iconNamed: #glamorousRedo
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRefresh [
	^ self iconNamed: #glamorousRefresh
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRemove [
	^ self iconNamed: #glamorousRemove
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRestart [
	^ self iconNamed: #glamorousRestart
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRight [
	^ self iconNamed: #glamorousRight
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousRightSide [
	^ self iconNamed: #glamorousRightSide
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousSave [
	^ self iconNamed: #glamorousSave
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousSaveToUrl [
	^ self iconNamed: #glamorousSaveToUrl
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousSearch [
	^ self iconNamed: #glamorousSearch
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousSpawn [
	^ self iconNamed: #glamorousSpawn
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousThrough [
	^ self iconNamed: #glamorousThrough
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousTrash [
	^ self iconNamed: #glamorousTrash
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousUndo [
	^ self iconNamed: #glamorousUndo
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousUp [
	^ self iconNamed: #glamorousUp
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousZoomIn [
	^ self iconNamed: #glamorousZoomIn
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousZoomOut [
	^ self iconNamed: #glamorousZoomOut
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamorousZoomToFit [
	^ self iconNamed: #glamorousZoomToFit
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamourousNextFailure [
	^ self iconNamed: #glamourousNextFailure
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamourousNextParser [
	^ self iconNamed: #glamourousNextParser
]

{
	#category : #icons,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>glamourousNextProduction [
	^ self iconNamed: #glamourousNextProduction
]

{
	#category : #utils,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>icons [
	^ icons ifNil: [icons := Dictionary new] 
]

{
	#category : #utils,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMUIThemeExtraIcons class>>resetIcons [
	icons := nil
]
