"

"
Class {
	#name : #GLMDropDownListMorphSelectionChanged,
	#superclass : #Announcement,
	#instVars : [
		'selectionIndex',
		'selectionValue'
	],
	#category : #Glamour-Morphic-Widgets,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMDropDownListMorphSelectionChanged>>selectionIndex [
	^ selectionIndex
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMDropDownListMorphSelectionChanged>>selectionIndex: anInteger [
	selectionIndex := anInteger
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMDropDownListMorphSelectionChanged>>selectionValue [
	^ selectionValue
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMDropDownListMorphSelectionChanged>>selectionValue: anObject [
	selectionValue := anObject
]
