"

"
Class {
	#name : #GLMTreeMorphStrongSelectionChanged,
	#superclass : #Announcement,
	#instVars : [
		'strongSelectionValue'
	],
	#category : #Glamour-Morphic-Widgets,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMTreeMorphStrongSelectionChanged>>strongSelectionValue [
	^ strongSelectionValue
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMTreeMorphStrongSelectionChanged>>strongSelectionValue: anObject [
	strongSelectionValue := anObject
]
