"
MultiByteFileStreamFileOutTestClass is used in MultiByteFileStreamTest>>#testFileOutNonAscii.

"
Class {
	#name : #MultiByteFileStreamFileOutTestClass,
	#superclass : #Object,
	#category : #Multilingual-Tests-TextConversion,
	#timestamp : 'SvenVanCaekenberghe 11/24/2014 14:45'
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:43'
}
MultiByteFileStreamFileOutTestClass class>>scriptName [
    ^'tété'
]
