"

"
Class {
	#name : #MetacelloSymbolicVersionSpec,
	#superclass : #MetacelloMethodSection,
	#instVars : [
		'versionString'
	],
	#category : #Metacello-Core-Constructors,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 07:16:49'
}
MetacelloSymbolicVersionSpec>>versionString [
	^ versionString
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 07:16:49'
}
MetacelloSymbolicVersionSpec>>versionString: anObject [
	versionString := anObject
]
