Extension {
	#name : #MetacelloSpecTestCase
}

{
	#category : #'*metacello-testsmccore',
	#timestamp : ' 8/31/2017 05:26:32'
}
MetacelloSpecTestCase>>packageSpec [
    ^ self project packageSpec
]

{
	#category : #'*metacello-testsmccore',
	#timestamp : ' 8/31/2017 05:26:32'
}
MetacelloSpecTestCase>>repositoriesSpec [
    ^ self project repositoriesSpec
]

{
	#category : #'*metacello-testsmccore',
	#timestamp : ' 8/31/2017 05:26:32'
}
MetacelloSpecTestCase>>repositorySpec [
    ^ self project repositorySpec
]
