Extension {
	#name : #Object
}

{
	#category : #'*Spec-Core',
	#timestamp : ' 8/31/2017 05:26:18'
}
Object>>asWidget [

	^ self
]

{
	#category : #'*Spec-Core',
	#timestamp : ' 8/31/2017 05:26:18'
}
Object>>isSpecAdapter [

	^ false
]

{
	#category : #'*Spec-Core',
	#timestamp : ' 8/31/2017 05:26:18'
}
Object>>isSpecContainer [
	^ false
]

{
	#category : #'*Spec-Core',
	#timestamp : ' 8/31/2017 05:26:18'
}
Object>>isSpecLayout [

	^ false
]

{
	#category : #'*Spec-Core',
	#timestamp : ' 8/31/2017 05:26:18'
}
Object>>isTreeNodeModel [

	^ false
]
