"
Browser is closing
"
Class {
	#name : #GLMBrowserClosing,
	#superclass : #Announcement,
	#instVars : [
		'presentation'
	],
	#category : #Glamour-Browsers-Announcements,
	#timestamp : 'TorstenBergmann 3/10/2015 21:58'
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:33'
}
GLMBrowserClosing>>presentation [
	^ presentation
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:33'
}
GLMBrowserClosing>>presentation: anObject [
	presentation := anObject
]
