"

"
Class {
	#name : #WriteBarrierStub,
	#superclass : #Object,
	#instVars : [
		'var1',
		'var2',
		'var3',
		'var4',
		'var5',
		'var6',
		'var7',
		'var8',
		'var9',
		'var10'
	],
	#category : #WriteBarrierTests,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:47'
}
WriteBarrierStub>>var1 [
	^ var1
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:47'
}
WriteBarrierStub>>var10 [
	^ var10
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:47'
}
WriteBarrierStub>>var10: anObject [
	var10 := anObject
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:47'
}
WriteBarrierStub>>var1: anObject [
	var1 := anObject
]
