"
I am the entrance door to the ocompletion algorithm. 
I can resolve the queried sequences and retrieve a list of answers according to ocompletion algorithm based on the last accepted sequences from the user.

"
Class {
	#name : #NOCController,
	#superclass : #NECController,
	#category : #NECompletion-OCompletion,
	#timestamp : '<historical>'
}

{
	#category : #private,
	#timestamp : ' 8/31/2017 05:26:21'
}
NOCController>>contextClass [
	^NOCContext
]

{
	#category : #private,
	#timestamp : ' 8/31/2017 05:26:21'
}
NOCController>>menuMorphClass [
	^ NOCMenuMorph
]
