"

"
Class {
	#name : #RBClassToRename,
	#superclass : #Model,
	#instVars : [
		'rewriteRule',
		'builder',
		'class'
	],
	#classInstVars : [
		'notUsed'
	],
	#category : #Refactoring-Tests-Core-Data,
	#timestamp : ''
}

{
	#category : #performing,
	#timestamp : ' 8/31/2017 05:26:31'
}
RBClassToRename>>method1 [
	^self method2
]

{
	#category : #performing,
	#timestamp : ' 8/31/2017 05:26:31'
}
RBClassToRename>>method2 [
	^self method1
]
