Extension {
	#name : #UITheme
}

{
	#category : #'*Polymorph-Widgets-Themes',
	#timestamp : ' 8/31/2017 05:26:15'
}
UITheme>>configureWatcherWindowLabelAreaFor: aWindow [
	^ self configureWindowLabelAreaFor: aWindow
]

{
	#category : #'*Polymorph-Widgets-Themes',
	#timestamp : ' 8/31/2017 05:26:15'
}
UITheme>>watcherWindowActiveFillStyleFor: aWindow [

	^ self windowActiveFillStyleFor: aWindow
]

{
	#category : #'*Polymorph-Widgets-Themes',
	#timestamp : ' 8/31/2017 05:26:15'
}
UITheme>>watcherWindowInactiveFillStyleFor: aWindow [

	^ self windowInactiveFillStyleFor: aWindow
]
