"

"
Class {
	#name : #GLMActionBrickDarkThemer,
	#superclass : #GLMBrickDarkThemer,
	#category : #Glamour-Morphic-Brick-Theme,
	#timestamp : ''
}

{
	#category : #brick-scrollbar,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMActionBrickDarkThemer>>scrollbarWidth [

	^ 2
]

{
	#category : #brick-scrollpane,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMActionBrickDarkThemer>>scrollpaneBackgroundColor [

	^ Color transparent
]
