"

"
Class {
	#name : #GLMBrickPopupHelpThemer,
	#superclass : #GLMBrickPopupThemer,
	#category : #Glamour-Morphic-Brick-Widgets-UI-Popup-Themer,
	#timestamp : ''
}

{
	#category : #brick-popup,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMBrickPopupHelpThemer>>backgroundColor [

	^ Color r: 220 g: 246 b: 255 range: 255
]

{
	#category : #brick-popup,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMBrickPopupHelpThemer>>borderColor [

	^ Color r: 48 g:194 b:240 range: 255
]

{
	#category : #brick-popup,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMBrickPopupHelpThemer>>textColor [

	^ Color r: 16 g: 172 b: 221 range: 255
]
