"

"
Class {
	#name : #GLMFormSubmitted,
	#superclass : #Announcement,
	#instVars : [
		'result'
	],
	#category : #Glamour-Morphic-Brick-Announcements,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMFormSubmitted>>result [
	^ result
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:34'
}
GLMFormSubmitted>>result: anObject [
	result := anObject
]
