Extension {
	#name : #Object
}

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>asBrick [

	^ GLMMorphBrick on: self asMorph
]

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>brickAlert [

	GLMAlertBrick alert: self
]

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>brickValue: aBrick [

	^ self
]

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>brickValue: anObject withEnoughArguments: aCollection [

	^ self
]

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>phlowValue: anObject [

	^ self
]

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>phlowValue: anObject value: otherObject [

	^ self
]

{
	#category : #'*Glamour-Morphic-Brick',
	#timestamp : ' 8/31/2017 05:26:34'
}
Object>>phlowValue: anObject withEnoughArguments: aCollection [

	^ self
]
