"

"
Class {
	#name : #GTSpotterDiveInElement,
	#superclass : #Announcement,
	#instVars : [
		'element',
		'eventType'
	],
	#category : #GT-Spotter-Announcements,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:36'
}
GTSpotterDiveInElement>>element [
	^ element
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:36'
}
GTSpotterDiveInElement>>element: anObject [
	element := anObject
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:36'
}
GTSpotterDiveInElement>>eventType [
	^ eventType
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:36'
}
GTSpotterDiveInElement>>eventType: anObject [
	eventType := anObject
]
