"

"
Class {
	#name : #GTSpotterAllCandidatesAdded,
	#superclass : #GTSpotterAnnouncement,
	#instVars : [
		'candidateLinks'
	],
	#category : #GT-Spotter-Announcements,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:36'
}
GTSpotterAllCandidatesAdded>>candidateLinks [
	^ candidateLinks
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:36'
}
GTSpotterAllCandidatesAdded>>candidateLinks: anObject [
	candidateLinks := anObject
]
