"
I am an interface (abstract) used for visiting the raw SDL2 events. 

"
Class {
	#name : #SDL2EventHandler,
	#superclass : #Object,
	#category : #OSWindow-SDL2,
	#timestamp : '<historical>'
}

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitCommonEvent: commonEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitControllerAxisEvent: controllerAxisEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitControllerButtonDownEvent: controllerButtonEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitControllerButtonUpEvent: controllerButtonEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitControllerDeviceAddedEvent: controllerDeviceEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitControllerDeviceRemappedEvent: controllerDeviceEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitControllerDeviceRemovedEvent: controllerDeviceEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitJoyAxisEvent: windowEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitJoyButtonDownEvent: windowEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitJoyButtonUpEvent: windowEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitJoyDeviceAddedEvent: joyDeviceEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitJoyDeviceRemovedEvent: joyDeviceEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitKeyDownEvent: windowEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitKeyUpEvent: windowEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitMouseButtonDownEvent: mouseMotionEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitMouseButtonUpEvent: mouseMotionEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitMouseMotionEvent: mouseMotionEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitMouseWheelEvent: mouseMotionEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitTextInputEvent: windowEvent [

]

{
	#category : #visitor,
	#timestamp : ' 8/31/2017 05:26:40'
}
SDL2EventHandler>>visitWindowEvent: windowEvent [

]
