"

"
Class {
	#name : #GLMPageSwitched,
	#superclass : #Announcement,
	#instVars : [
		'smooth',
		'pageIndex'
	],
	#category : #Glamour-Morphic-Pager-Announcement,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPageSwitched>>pageIndex [
	^ pageIndex
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPageSwitched>>pageIndex: anObject [
	pageIndex := anObject
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPageSwitched>>smooth [
	^ smooth
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPageSwitched>>smooth: anObject [
	smooth := anObject
]
