"

"
Class {
	#name : #GLMPagePopedAndReplaced,
	#superclass : #Announcement,
	#instVars : [
		'brick'
	],
	#category : #Glamour-Morphic-Pager-Announcement,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPagePopedAndReplaced>>brick [
	^ brick
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPagePopedAndReplaced>>brick: anObject [
	brick := anObject
]
