"

"
Class {
	#name : #GLMPagerSynchronizeScrollAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'value'
	],
	#category : #Glamour-Morphic-Pager-Announcement,
	#timestamp : ''
}

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPagerSynchronizeScrollAnnouncement>>value [
	^ value
]

{
	#category : #accessing,
	#timestamp : ' 8/31/2017 05:26:35'
}
GLMPagerSynchronizeScrollAnnouncement>>value: anObject [
	value := anObject
]
